
export default function Assignment() {
  return (
    <>
      <p className='text-2xl self-start pt-8'>8. SECONDARY ASSIGNMENT</p>
      <p className='font-vista-sans py-2'>
        THE PRIMARY OWNER AND, WHERE APPLICABLE, ALL
        SUBSEQUENT OWNERS, SHALL HAVE THE RIGHT TO RESELL
        THE PURCHASED NFT (<strong className='font-hwt-artz'>“RESALE”</strong>), AND RELATED ART, ON A
        MARKETPLACE THAT ALLOWS THE PURCHASE AND SALE OF
        NFTS. THE OWNER SHALL PROVIDE ITS BEST EFFORTS TO
        RESELL THE PURCHASED NFT ON A MARKETPLACE WHICH (I)
        CRYPTOGRAPHICALLY VERIFIES EACH NFT OWNER&apos;S RIGHTS
        TO DISPLAY THE ART IN ORDER TO LIST IT FOR SALE, TO
        ENSURE THAT ONLY THE ACTUAL OWNER CAN DISPLAY THE
        ART FOR RESALE, AND (II) PROVIDES FOR A PERCENTAGE OF
        THE RESALE PRICE TO BE AUTOMATICALLY GRANTED TO THE
        CREATOR UPON RESALE.
        <br /><br />
        ANY SUCH SUBSEQUENT OWNER OR OWNER(S), SHALL HAVE
        THE RIGHT TO LICENSE, ASSIGN OR OTHERWISE TRANSFER TO
        A THIRD-PARTY ALL OR PART OF THE INTELLECTUAL
        PROPERTY RIGHTS ON THE ART HEREBY GRANTED AS PER THIS
        AGREEMENT, FOR ANY PURPOSE WHATSOEVER.
        <br /><br />
        IN CASE OF TRANSFER OF OWNERSHIP OF THE PURCHASED NFT,
        IN ANY WAY WHATSOEVER, INCLUDING RESALE, THE OWNER
        AGREES TO ASSIGN TO THE SUBSEQUENT BUYER OF THE
        PURCHASED NFT ALL RIGHTS ON THE RELATED ART DETAILED
        IN ARTICLE 3 OF THIS AGREEMENT, UNDER THE SAME
        CONDITIONS, TO THE EXTENT SUCH RIGHTS HAVE NOT BEEN
        PREVIOUSLY TRANSFERRED TO A THIRD-PARTY IN
        COMPLIANCE WITH THE AGREEMENT.
        <br /><br />
        THIS AGREEMENT SHALL GOVERN ANY RESALE AS LONG AS IT
        IS STILL ATTACHED TO THE PURCHASED NFT AND PROVIDED
        NO OTHER AGREEMENT HAS BEEN CONCLUDED BETWEEN THE
        OWNER AND THE SUBSEQUENT BUYER, WHICH SHALL ONLY
        APPLY BETWEEN THE PARTIES OF SAID AGREEMENT.
      </p>
    </>
  )
}