
export default function Compensation() {
  return (
    <>
      <p className='text-2xl self-start pt-8'>9. COMPENSATION</p>
      <p className='font-vista-sans py-2'>
        IT IS EXPRESSLY AGREED THAT ALL INTELLECTUAL PROPERTY
        RIGHTS ASSIGNED TO THE PRIMARY OWNER, AS PER THE
        PRIMARY ASSIGNMENT, OR TO THE SUBSEQUENT OWNERS, AS
        PER A SECONDARY ASSIGNMENT, ARE GRANTED IN
        CONSIDERATION OF THE PRICE PAID BY THE OWNER TO
        PURCHASE THE PURCHASED NFT, AS LISTED ON THE NFT
        MARKETPLACE ON WHICH IT IS ACQUIRED (THE “PURCHASE
        PRICE”), WHERE APPLICABLE, WHICH SHALL BE DEEMED FIXED
        AND DEFINITIVE.
        <br /><br />
        NOTWITHSTANDING THE FOREGOING, THE CREATOR SHALL
        ALSO BE ENTITLED TO A COMPENSATION ON ANY RESALE OF
        THE COMPLETE WORK IN ACCORDANCE WITH THE
        PERCENTAGE OF COMMISSION DETERMINED BY THE NFT
        MARKETPLACE ON WHICH SAID RESALE IS COMPLETED.
      </p>
    </>
  )
}