
export default function Cooperation() {
  return (
    <>
      <p className='text-2xl self-start pt-8'>12. COOPERATION</p>
      <p className='font-vista-sans py-2'>
        THE CREATOR AND THE OWNER SHALL COOPERATE IN GOOD
        FAITH AND REASONABLY ASSIST EACH OTHER IN THE
        PROSECUTION OF LEGAL PROCEEDINGS INVOLVING THE ART,
        OR DERIVATIVE WORKS THEREFROM, INCLUDING
        PROCEEDINGS CONDUCTED FOR THE PURPOSE OF PROTECTING
        ANY AND ALL INTELLECTUAL PROPERTY RIGHTS ON THE ART
        FROM INFRINGEMENT.
        <br /><br />
        THE CREATOR SHALL HAVE THE RIGHT TO PROTECT AND
        DEFEND, INCLUDING THROUGH LITIGATION, THE RIGHTS
        ATTACHED TO THE ART IN THE EVENT OF THE OWNER&apos;S
        INACTION ON WRITTEN NOTICE BY THE CREATOR TO THE
        OWNER.
      </p>
    </>
  )
}