
export default function Governing() {
  return (
    <>
      <p className='text-2xl self-start pt-8'>13. GOVERNING LAW</p>
      <p className='font-vista-sans py-2'>
        IF ANY PROVISION IN THIS AGREEMENT SHALL BE HELD TO BE
        ILLEGAL, INVALID OR UNENFORCEABLE, IN WHOLE OR IN PART,
        THE PROVISION SHALL APPLY WITH WHATEVER DELETION OR
        MODIFICATION IS NECESSARY SO THAT THE PROVISION IS
        LEGAL, VALID AND ENFORCEABLE AND GIVES EFFECT TO THE
        INITIAL INTENTION OF THE PARTIES.
        <br /><br />
        THE VALIDITY OF THIS AGREEMENT AND ANY OF ITS TERMS
        AND PROVISIONS, AS WELL AS THE RIGHTS AND DUTIES OF THE
        PARTIES HEREUNDER, SHALL BE GOVERNED, INTERPRETED
        AND ENFORCED IN ACCORDANCE WITH THE LAWS OF THE
        UNITED STATES OF AMERICA FOR FEDERAL LAW QUESTIONS
        AND THE STATE OF CALIFORNIA FOR STATE LAW QUESTIONS.
      </p>
    </>
  )
}