
export default function License() {
  return (
    <>
      <p className='text-2xl self-start pt-8'>4. ASSIGNMENT & LIMITED LICENSE USE</p>
      <p className='self-start font-hwt-artz py-2'>PERSONAL USE</p>
      <p className='font-vista-sans'>
        IN CONSIDERATION OF THE PURCHASE PRICE, AS DEFINED
        HEREINAFTER, AND SUBJECT TO THE PRIMARY OWNER&apos;S
        CONTINUED COMPLIANCE WITH THE TERMS OF THIS
        AGREEMENT AND ALL APPLICABLE LAWS, THE CREATOR
        HEREBY GRANTS A LIMITED, WORLDWIDE, NONEXCLUSIVE
        LICENSE TO THE PRIMARY OWNER TO COPY, ACCESS AND USE
        THEIR FROGGY FRIENDS NFT AND RELATED ART FOR THE
        PRIMARY OWNER&apos;S OWN PERSONAL, NON-COMMERCIAL USE,
        PROVIDED THAT THE PRIMARY OWNER KEEPS ALL COPYRIGHT
        AND OTHER PROPRIETARY NOTICES INTACT.
      </p>
      <p className='self-start font-hwt-artz py-2'>COMMERCIAL USE</p>
      <p className='font-vista-sans'>
        PRIMARY OWNER IS GRANTED A LIMITED, WORLDWIDE,
        NONEXCLUSIVE LICENSE TO COPY, ACCESS, USE AND
        OTHERWISE EXPLOIT THE PRIMARY OWNER&apos;S FROGGY FRIENDS
        NFT AND RELATED ART, FOR THE PURPOSE OF
        COMMERCIALIZING AND PROMOTING THEIR OWN GOODS AND
        SERVICES, WHICH SHALL INCLUDE THE RIGHT TO PRODUCE
        AND SELL GOODS AS WELL AS SERVICES THAT INCLUDES,
        CONTAINS, OR CONSISTS OF THE GRAPHICAL IMAGE OF THE
        PRIMARY OWNER&apos;S FROGGY FRIENDS NFT, PROVIDED THAT
        SUCH COMMERCIAL USE DOES NOT RESULT IN THE PRIMARY
        OWNER EARNING MORE THAN ONE HUNDRED THOUSAND
        DOLLARS ($500,000), OR ITS EQUIVALENT IN ETHEREUM OR ANY
        CURRENCY, IN GROSS REVENUE IN ANY TWELVE MONTH
        PERIOD, DIRECTLY OR INDIRECTLY, INCLUDING BUT NOT
        LIMITED TO THROUGH ANY AND ALL RELATED ENTITIES AND
        FAMILY MEMBERS, UNLESS AN EXEMPTION OR BROADER
        LICENSE IS EXPRESSLY GRANTED BY THE CREATOR.
        <br /><br />
        PRIMARY OWNER IS ALSO GRANTED A LIMITED, WORLDWIDE,
        NONEXCLUSIVE LICENSE TO COPY, ACCESS, USE AND
        OTHERWISE EXPLOIT THE PRIMARY OWNER&apos;S FROGGY FRIENDS
        NFT AND RELATED ART, INCLUDING BUT NOT LIMITED TO
        SUBLICENSING IT, FOR THE PURPOSE OF COMMERCIALIZING
        AND PROMOTING THIRD PARTY GOODS AND SERVICES IN A
        MANNER THAT INCLUDES, CONTAINS, OR CONSISTS OF THE
        GRAPHICAL IMAGE OF THE PRIMARY OWNER&apos;S FROGGY
        FRIENDS NFT, PROVIDED THAT SUCH COMMERCIAL USE DOES
        NOT RESULT IN THE SUBLICENSEE EARNING MORE THAN ONE
        HUNDRED THOUSAND DOLLARS ($500,000), OR ITS EQUIVALENT
        IN ETHEREUM OR ANY CURRENCY, FOR ANY PROJECT FOR
        WHICH IT TAKES A SUBLICENSE AND/OR OTHERWISE UTILIZES
        THE NFT AND RELATED ART, IN ANY TWELVE MONTH PERIOD,
        DIRECTLY OR INDIRECTLY, INCLUDING BUT NOT LIMITED TO
        THROUGH ANY AND ALL RELATED ENTITIES AND FAMILY
        MEMBERS, UNLESS AN EXEMPTION OR BROADER RIGHT TO
        SUBLICENSE IS EXPRESSLY GRANTED BY THE CREATOR.
      </p>
      <p className='self-start font-vista-sans py-2'>
        THIS LIMITED LICENSE FOR COMMERCIAL USE IS SUBJECT TO
        THE FOLLOWING CONDITIONS:
      </p>
      <ul className='font-vista-sans list-disc pl-4'>
        <li>
          PRIMARY OWNER AND/OR ANY SUBLICENSEE DOES NOT
          HAVE ANY RIGHT TO MODIFY OR PRESENT ITS FROGGY
          FRIENDS NFT OR RELATED ART IN ANY WAY OR ANY
          CONTEXT THAT DEPICTS HATRED, INTOLERANCE,
          VIOLENCE, CRUELTY, OR ANYTHING ELSE THAT COULD
          REASONABLY BE FOUND TO CONSTITUTE HATE SPEECH,
          BE OFFENSIVE, DEMEANING, NOT COMPORT WITH THE
          INCLUSIVE VALUES OF THE FROGGY FRIENDS BRAND AND
          COMMUNITY, OR OTHERWISE INFRINGE UPON THE RIGHTS
          OF OTHERS OR THE FROGGY FRIENDS COMMUNITY;
        </li>
        <li>
          PRIMARY OWNER MAY NOT USE AND/OR SUBLICENSE
          THEIR FROGGY FRIENDS NFT OR RELATED ART TO
          PROMOTE, ADVERTISE, MARKET, OR SELL ANY THIRD
          PARTY GOOD OR SERVICE WITHOUT SUCH USE AND/OR
          SUBLICENSE BEING EXPRESSLY APPROVED BY THE
          CREATOR;
        </li>
        <li>
          PRIMARY OWNER MAY NOT USE THE NAME “FROGGY
          FRIENDS OR ANY FROGGY FRIENDS NAME, LOGO OR
          TRADEMARK, THE NAME OF ANY FROGGY FRIENDS
          CHARACTERS (AS APPLICABLE), OR ANY ANIMATION,
          CHARACTERS, THEMES OR OTHER MATERIAL RELATED TO
          THE CREATOR&apos;S OWN DIGITAL CONTENT; AND
        </li>
        <li>
          PRIMARY OWNER MAY NOT COMBINE ITS FROGGY FRIEND
          WITH ANY OTHER FROGGY FRIENDS OR MODIFIED
          FROGGY FRIEND THAT IT DOES NOT OWN, EXCEPT ON
          EXPLICIT PERMISSION OF THE OTHER FROGGY FRIENDS
          OWNER; AND
        </li>
        <li>
          THE PRIMARY OWNER MAY NOT ATTEMPT TO
          TRADEMARK, COPYRIGHT, OR OTHERWISE ACQUIRE
          ADDITIONAL INTELLECTUAL PROPERTY RIGHTS IN OR TO
          “FROGGY FRIENDS” OR ANY FROGGY FRIENDS NFT OR
          RELATED ART OR CONTENT.
        </li>
        <li>
          FOR THE AVOIDANCE OF DOUBT, NOTHING CONTAINED IN
          THIS AGREEMENT SHALL GRANT OR SHALL BE DEEMED
          TO GRANT ANY RIGHT ON THE ART&apos;S ATTRIBUTES, WHICH
          SHALL REMAIN THE EXCLUSIVE PROPERTY OF THE
          CREATOR.
        </li>
      </ul>
    </>
  )
}