
export default function Moral() {
  return (
    <>
      <p className='text-2xl self-start pt-8'>10. MORAL RIGHTS</p>
      <p className='font-vista-sans py-2'>
        THE CREATOR SHALL HAVE THE RIGHT TO ENFORCE, ON
        BEHALF OF THE AUTHOR, ALL MORAL RIGHTS OF THE AUTHOR
        OF THE ART, AS PROVIDED BY APPLICABLE LAW, WHICH SHALL
        REMAIN PERPETUAL, INALIENABLE, IMPRESCRIPTIBLE AND, IN
        GENERAL, ABSOLUTE.
        <br /><br />
        THE OWNER HEREBY UNDERTAKES TO ABIDE, AND MAKE ITS
        CONTRACTORS, INCLUDING LICENSEES, SUBLICENSEES,
        SUBSEQUENT BUYERS, AND THIRD PARTIES ABIDE BY THE
        AUTHOR&apos;S MORAL RIGHTS IN ANY AND ALL USE OF THE ART,
        AND IN PARTICULAR THE FOLLOWING RIGHTS:
        <br /><br />
        (I) RIGHT OF AUTHORSHIP, WHICH SHALL ENTITLE THE
        CREATOR TO DEMAND AND CLAIM AT ANY TIME THAT THE
        AUTHOR&apos;S CHOSEN NAME BE MENTIONED ON ANY MODE OF
        PUBLICATION OF THE ART; AND
        <br /><br />
        (II) RIGHT TO PRESERVE THE INTEGRITY OF THE ART, WHICH
        SHALL ENTITLE THE CREATOR TO OPPOSE ANY MODIFICATION,
        DELETION OR ADDITION LIKELY TO ALTER THE ART, OR ANY
        USE OF THE ART THAT MAY ALTER ITS SPIRIT, DEVALUATE IT
        OR OTHERWISE BE DEEMED PREJUDICIAL TO THE REPUTATION
        OF THE CREATOR OR THE FROGGY FRIENDS BRAND OR
        COMMUNITY.
      </p>
    </>
  )
}