
export default function Ownership() {
  return (
    <>
      <p className='text-2xl self-start pt-8'>7. OWNERSHIP RIGHTS</p>
      <p className='font-vista-sans py-2'>
        THE PURCHASE OF A FROGGY FRIENDS NFT MEANS THAT THE
        PRIMARY OWNER HAS FULL OWNERSHIP RIGHTS IN THE
        FROGGY FRIENDS NFT, INCLUDING THE RIGHT TO STORE, SELL
        AND TRANSFER THE NFT. HOWEVER, PRIMARY OWNER
        ACKNOWLEDGES AND AGREES THAT THIS PURCHASE OF THE
        FROGGY FRIENDS NFT DOES NOT PROVIDE ANY RIGHTS,
        EXPRESS OR IMPLIED, IN (INCLUDING, WITHOUT LIMITATION,
        ANY COPYRIGHTS OR OTHER INTELLECTUAL PROPERTY RIGHTS
        IN OR TO) THE FROGGY FRIENDS ASSOCIATED WITH THE NFT
        OTHER THAN THE LIMITED LICENSES GRANTED IN SECTION 3
        AND 4 ABOVE. THE PRIMARY OWNER&apos;S RIGHTS AND INTEREST
        IN ITS FROGGY FRIENDS NFT, ITS ASSOCIATED FROGGY
        FRIENDS, ANY DERIVATIVE FROGGY FRIENDS, AND ANY ART
        PROVIDED BY THESE TERMS WILL IMMEDIATELY TERMINATE
        UPON ANY SUBSEQUENT SALE, TRANSFER, DISPOSSESSION,
        BURNING, OR OTHER RELINQUISHMENT OF THEIR FROGGY
        FRIENDS NFT.
        <br /><br />
        ANY USE OF THE ART OTHER THAN AS EXPRESSLY
        AUTHORIZED HEREIN, WITHOUT THE PRIOR EXPLICIT WRITTEN
        PERMISSION OF THE CREATOR, IS STRICTLY PROHIBITED AND
        SHALL IMMEDIATELY TERMINATE THE RIGHT TO ACCESS AND
        USE THE FROGGY FRIENDS WEBSITE (AS DEFINED IN FROGGY
        FRIENDS TERMS OF SERVICE) AND ALL RIGHTS AND LICENSES
        GRANTED BY THESE TERMS. SUCH UNAUTHORIZED USE MAY
        ALSO VIOLATE APPLICABLE LAWS INCLUDING COPYRIGHT AND
        TRADEMARK LAWS AND APPLICABLE COMMUNICATIONS
        REGULATIONS AND STATUTES.
        <br /><br />
        NOTHING IN THIS AGREEMENT SHALL BE INTERPRETED AS
        GRANTING ANY LICENSE OF INTELLECTUAL PROPERTY RIGHTS
        TO YOU OTHER THAN AS EXPLICITLY SET FORTH IN THIS
        AGREEMENT.
      </p>
    </>
  )
}