import Link from "next/link";

export default function Projects() {
  return (
    <>
      <p className='text-2xl self-start pt-8'>3. SHARING YOUR FROGGY FRIENDS & PROMOTING YOUR FROGGY FRIENDS PROJECTS</p>
      <p className='font-vista-sans py-2'>
        AS A COMPANY, WE THRIVE WHEN OUR COMMUNITY THRIVES.
        WE WANT TO KNOW ABOUT YOU AND YOUR FROGGY FRIENDS!
        PLEASE SEND US ANY PICTURES, ART, SCREENSHOTS, ETC. OF
        YOU AND YOUR FRIENDS AND FAMILY WITH YOUR FROGGY
        FRIENDS; IF YOU ARE OPEN TO US RESHARING THEM, SUBMIT
        THEM <Link className='text-dark-blue font-bold' href='/projects'>HERE</Link>. WE ALSO WANT TO KNOW ABOUT AND CONSIDER
        PROMOTING YOUR FROGGY FRIENDS NFT PROJECTS, WHERE
        APPROPRIATE, REGARDLESS OF WHETHER THOSE PROJECTS
        ARE FOR YOUR OWN PERSONAL, NON-COMMERCIAL USE, OR
        WHETHER THEY ARE COMMERCIAL PROJECTS. IF YOU ARE
        GETTING STARTED ON A PROJECT WHERE YOU INTEND TO
        MAKE COMMERCIAL USE OF YOUR FROGGY FRIENDS NFT AND
        RELATED ART, PLEASE LET US KNOW BY DESCRIBING YOUR
        PROJECT, <Link className='text-dark-blue font-bold' href='/projects'>HERE</Link>, SO THAT WE CAN ENSURE THAT YOUR
        PROJECT COMPLIES WITH THIS AGREEMENT, APPROVE IT, AND
        IF IT DOES, SO WE CAN DETERMINE HOW WE CAN BEST
        SUPPORT YOU. SIMILARLY, IF YOU EXPECT TO EXCEED THE
        $500,000 LIMITATIONS ON ANNUAL GROSS REVENUE FROM
        COMMERCIAL USE SET FORTH BELOW, IN ORDER TO ENSURE
        YOU DO NOT BREACH THIS AGREEMENT AND THE LICENSE
        CONVEYED, WITHIN FIFTEEN (15) DAYS OF YOUR HAVING A
        REASONABLE EXPECTATION OF EXCEEDING THAT THRESHOLD,
        PLEASE CONTACT US <Link className='text-dark-blue font-bold' href='/projects'>HERE</Link> AND EMAIL US AT [EMAIL
        PROTECTED], TO REQUEST A DISCUSSION REGARDING
        ENTERING INTO A BROADER LICENSE AGREEMENT OR
        OBTAINING AN EXEMPTION. AS THE CREATOR, WE RETAIN
        AUDITING AND ACCOUNTING RIGHTS, AUTHORITY AND SOLE
        DISCRETION TO GRANT OR DENY EXEMPTIONS, AS WELL AS TO
        GRANT OR DENY FURTHER OR BROADER LICENSES.
      </p>
    </>
  )
}