
export default function Purpose() {
  return (
    <>
      <p className='text-2xl self-start pt-8'>2. PURPOSE</p>
      <p className='font-vista-sans py-2'>
        THIS OWNERSHIP ASSIGNMENT AGREEMENT IS INTENDED TO
        GOVERN THE TERMS AND CONDITIONS OF ASSIGNMENT OF
        RIGHTS, TITLE AND INTEREST IN AND TO THE INTELLECTUAL
        PROPERTY RIGHTS ON THE ART TO WHICH THIS AGREEMENT IS
        ATTACHED (HEREINAFTER THE <strong className='font-hwt-artz'>“AGREEMENT”</strong> ).
        <br /><br />
        THE AGREEMENT SHALL GOVERN THE PRIMARY ASSIGNMENT
        UNDER WHICH THE CREATOR ASSIGNS TO THE PRIMARY
        OWNER CERTAIN INTELLECTUAL PROPERTY RIGHTS ON THE
        ART AND ALL SECONDARY ASSIGNMENTS BETWEEN THE
        OWNER AND SUBSEQUENT BUYERS OF THE PURCHASED NFT,
        WHERE APPLICABLE.
        <br /><br />
        THE AGREEMENT SHALL BE EFFECTIVE AS OF THE EFFECTIVE
        DATE AND REMAIN IN FORCE AS LONG AS IT IS STILL
        ATTACHED TO THE PURCHASED NFT. BY ACQUIRING THE
        PURCHASED NFT, AND RELATED ART, IN ANY WAY
        WHATSOEVER, THE OWNER HEREBY ACKNOWLEDGES HAVING
        READ THE CONTENT OF THIS AGREEMENT AND AGREES TO
        ABIDE BY ITS TERMS AND CONDITIONS SET FORTH HEREIN.
        <br /><br />
        THIS AGREEMENT SHALL APPLY TO THE PRIMARY ASSIGNMENT
        AND ALL SECONDARY ASSIGNMENTS TO THE EXTENT NO
        OTHER WRITTEN AGREEMENT HAS BEEN CONCLUDED
        BETWEEN THE PARTIES TO SUCH ASSIGNMENT. IN CASE OF
        CONTRADICTION BETWEEN A SPECIFIC AGREEMENT AND A
        GENERAL AGREEMENT, THE PROVISIONS OF THE SPECIFIC
        AGREEMENT SHALL PREVAIL.
        <br /><br />
        IN CREATING THIS AGREEMENT, WE ACKNOWLEDGE THAT THE
        WAY PEOPLE CREATE, USE, AND MONETIZE THEIR NFTS IS
        EVOLVING AND CHANGING. WE HAVE DEVELOPED THIS
        AGREEMENT SEEKING TO PROTECT THE HARD WORK AND
        CREATIVITY OF THE CREATORS, ON THE ONE HAND, WHILE
        GRANTING OWNERS THE FREEDOM AND FLEXIBILITY TO FULLY
        ENJOY THEIR FROGGY FRIENDS NFTS AND RELATED ART. WE
        ARE OPEN TO OUR COMMUNITY&apos;S FEEDBACK ON THIS
        AGREEMENT AND MAY WELL REVISE IT AND PUBLISH
        AMENDED VERSIONS FROM TIME TO TIME.
      </p>
    </>
  )
}