
export default function Termination() {
  return (
    <>
      <p className='text-2xl self-start pt-8'>6. TERMS AND TERMINATION</p>
      <p className='font-vista-sans py-2'>
        THE FOREGOING LIMITED LICENSES APPLY ONLY DURING THE
        PERIOD THAT THE PRIMARY OWNER OWNS THE FROGGY
        FRIENDS NFT ASSOCIATED WITH ITS FROGGY FRIENDS. THESE
        LICENSES TERMINATE IMMEDIATELY AT SUCH A POINT THAT
        THE PRIMARY OWNER NO LONGER OWNS ITS FROGGY FRIENDS
        NFT. MOREOVER, IF YOU EXCEED THE SCOPE OF THE LICENSES
        GRANTED IN SECTIONS 3 AND 4 HEREIN WITHOUT ENTERING
        INTO A BROADER LICENSE AGREEMENT WITH OR OBTAINING
        AN EXEMPTION, YOU ACKNOWLEDGE AND AGREE THAT: (I)
        YOU ARE IN BREACH OF THIS LICENSE; (II) IN ADDITION TO ANY
        REMEDIES THAT MAY BE AVAILABLE TO CREATOR AT LAW OR
        IN EQUITY, THE CREATOR MAY IMMEDIATELY TERMINATE THIS
        LICENSE, WITHOUT THE REQUIREMENT OF NOTICE; AND (III)
        YOU WILL BE RESPONSIBLE TO REIMBURSE CREATOR FOR ANY
        FEES, COSTS AND EXPENSES INCURRED BY CREATOR DURING
        THE COURSE OF ENFORCING THE TERMS OF THIS LICENSE
        AGAINST YOU, INCLUDING BUT NOT LIMITED TO ACCOUNTING
        AND LEGAL FEES, COSTS AND EXPENSES.
      </p>
    </>
  )
}