
export default function Trademark() {
  return (
    <>
      <p className='text-2xl self-start pt-8'>11. TRADEMARKS AND PROMOTION</p>
      <p className='font-vista-sans py-2'>
        WHEN USING THE FROGGY FRIENDS NFTS AND RELATED ART,
        IN ANY WAY WHATSOEVER, INCLUDING BUT NOT LIMITED TO
        ITS PUBLICATION, EXPLOITATION, AND/OR PROMOTION, THE
        OWNER SHALL NOT USE THE TRADEMARKS, SERVICE MARKS,
        OR PROPRIETARY WORDS OR SYMBOLS OF THE CREATOR, TO
        THE EXTENT OTHERWISE PERMITTED BY APPLICABLE LAW OR
        BY WRITTEN AGREEMENT OF THE CREATOR.
        <br /><br />
        BY EXCEPTION, WHEN USING THE ART FOR NON-COMMERCIAL
        PURPOSES ONLY, THE OWNER SHALL HAVE THE RIGHT TO
        REFERENCE THE CREATOR BY USING THE DENOMINATION
        “FROGGY FRIENDS” OR OTHER DENOMINATION(S) THAT THE
        CREATOR MAY DIRECT FROM TIME TO TIME, UNLESS
        INFORMED OTHERWISE BY THE CREATOR. OWNER SHALL TAKE
        CARE THAT SUCH USE SHALL NOT, IN ANY WAY WHATSOEVER,
        DAMAGE OR ADVERSELY IMPACT THE CREATOR&apos;S
        REPUTATION, THE FROGGY FRIENDS BRAND OR COMMUNITY.
        <br /><br />
        THE CREATOR SHALL HAVE THE RIGHT BUT NOT THE
        OBLIGATION, AT ITS SOLE DISCRETION, TO PROMOTE
        (INCLUDING THROUGH SOCIAL MEDIA) ANY PUBLIC USE OF THE
        ART BY THE OWNER, UNLESS THE OWNER INFORMS THE
        CREATOR OTHERWISE. THE OWNER SHALL NOT USE THE ART IN
        A WAY THAT WOULD OR COULD PRESENT THE CREATOR AS
        ENDORSING, RECOMMENDING OR FAVORING, IN ANY WAY
        WHATSOEVER, THE OWNER AND/OR ITS USE OF THE ART,
        WITHOUT THE CONSENT AND PERMISSION OF THE CREATOR.
        <br /><br />
        THE TRADEMARKS, SERVICE MARKS, TRADE NAMES AND
        LOGOS, INCLUDING FROGGY FRIENDS, AND ANY THIRD-PARTY
        MARKS USED AND DISPLAYED THROUGH THE SERVICES ARE
        TRADEMARKS OF THE CREATOR, ITS LICENSORS, AFFILIATES
        OR SPONSORS, AND MAY NOT BE USED BY A PRIMARY OWNER
        OTHER THAN TO FACTUALLY DESCRIBE ITS FROGGY FRIENDS
        NFT OR FROGGY FRIENDS ENHANCEMENT WHEN LISTING IT
        FOR SALE OR DISTRIBUTION OR FOR NON-COMMERCIAL
        PURPOSES. WE RETAIN THE RIGHT TO MONITOR AND POLICE
        THE USE OF OUR TRADEMARKS, INCLUDING BUT NOT LIMITED
        TO: (A) TAKE ALL REASONABLE MEASURES, INCLUDING
        WITHOUT LIMITATIONS BRINGING CIVIL ACTIONS FOR
        TRADEMARK INFRINGEMENT, TO STOP THE USE OF MARKS
        WHICH, IN OUR SOLE JUDGMENT, ARE THE SAME AS OR
        CONFUSINGLY SIMILAR TO OUR TRADEMARKS AND (B) TAKE
        ALL REASONABLE MEASURES, INCLUDING WITHOUT
        LIMITATIONS BRINGING PROCEEDINGS IN THE UNITED STATES
        PATENT AND TRADEMARK OFFICE OR ELSEWHERE, TO
        PREVENT THE REGISTRATION OF MARKS WHICH, IN OUR SOLE
        JUDGMENT, ARE THE SAME AS OR CONFUSINGLY SIMILAR TO
        THE TRADEMARKS.
      </p>
    </>
  )
}