
export default function Warranties() {
  return (
    <>
      <p className='text-2xl self-start pt-8'>5. WARRANTIES AND INDEMNIFICATION</p>
      <p className='font-vista-sans py-2'>
        IN THE EVENT THAT A PRIMARY OWNER MAKES USE OF THE
        LIMITED, WORLDWIDE, NONEXCLUSIVE LICENSE TO COPY,
        ACCESS, USE AND OTHERWISE EXPLOIT THE PRIMARY OWNER&apos;S
        FROGGY FRIENDS NFT AND RELATED ART FOR THEIR OWN
        COMMERCIAL PURPOSES AS ALLOWED FOR BY THIS
        AGREEMENT, PRIMARY OWNER REPRESENTS AND WARRANTS
        THAT THEY WILL TAKE ALL NECESSARY STEPS TO UNDERTAKE
        THEIR COMMERCIAL ACTIVITIES IN A LEGAL MANNER,
        INCLUDING BUT NOT LIMITED TO FORMING ANY NEEDED
        CORPORATE ENTITY, BECOMING DULY ORGANIZED, VALIDLY
        EXISTING AND DULY QUALIFIED TO DO BUSINESS IN ALL
        JURISDICTIONS WHERE THOSE ACTIVITIES ARE CARRIED OUT,
        AS WELL AS REMAINING IN GOOD STANDING UNDER AND
        ABIDING BY ALL APPLICABLE LAWS, RULES AND REGULATIONS
        THAT RELATE TO THOSE ACTIVITIES. PRIMARY OWNER ALSO
        REPRESENTS AND WARRANTS THAT THEY HAVE REQUISITE
        POWER AND AUTHORITY TO CARRY OUT THEIR COMMERCIAL
        ACTIVITIES, AND THAT INCLUDES BUT IS NOT LIMITED TO,
        HAVING SUFFICIENT INSURANCE TO ENSURE THEY CAN MEET
        THEIR OBLIGATIONS TO THEIR CUSTOMERS AND
        INDEMNIFICATION OBLIGATIONS TO THE CREATORS.
        <br /><br />
        IN THE EVENT THAT A PRIMARY OWNER MAKES USE OF THE
        LIMITED, WORLDWIDE, NONEXCLUSIVE LICENSE TO COPY,
        ACCESS, USE AND OTHERWISE EXPLOIT THE PRIMARY OWNER&apos;S
        FROGGY FRIENDS NFT AND RELATED ART BY GRANTING A
        SUBLICENSE AND/OR OTHERWISE ALLOWING THIRD PARTIES
        TO USE THEIR FROGGY FRIENDS NFT AS ALLOWED FOR BY THIS
        AGREEMENT, PRIMARY OWNER REPRESENTS AND WARRANTS
        THAT THEY WILL TAKE ALL NECESSARY STEPS TO ENSURE
        THAT THE THIRD PARTY IS UNDERTAKING THEIR COMMERCIAL
        ACTIVITIES IN A LEGAL MANNER, INCLUDING BUT NOT LIMITED
        TO FORMING ANY NEEDED CORPORATE ENTITY, BECOMING
        DULY ORGANIZED, VALIDLY EXISTING AND DULY QUALIFIED
        TO DO BUSINESS IN ALL JURISDICTIONS WHERE THOSE
        ACTIVITIES ARE CARRIED OUT, AS WELL AS REMAINING IN
        GOOD STANDING UNDER AND ABIDING BY ALL APPLICABLE
        LAWS, RULES AND REGULATIONS THAT RELATE TO THOSE
        ACTIVITIES. PRIMARY OWNER ALSO REPRESENTS AND
        WARRANTS THAT THEY HAVE REQUISITE POWER AND
        AUTHORITY TO CARRY OUT THEIR COMMERCIAL ACTIVITIES,
        AND THAT INCLUDES BUT IS NOT LIMITED TO, HAVING
        SUFFICIENT INSURANCE TO ENSURE THEY CAN MEET THEIR
        OBLIGATIONS TO THEIR CUSTOMERS AND INDEMNIFICATION
        OBLIGATIONS TO THE CREATORS.
        <br /><br />
        MOREOVER, THE PRIMARY OWNER (THE “INDEMNIFYING
        PARTY”) SHALL INDEMNIFY, DEFEND, AND HOLD HARMLESS
        THE CREATOR FROM AND AGAINST ANY LOSSES, DAMAGES,
        CLAIMS, ACTIONS, DEMANDS, JUDGMENTS, LIABILITY AND/OR
        SUITS INCLUDING REASONABLE ATTORNEYS&apos; FEES, AS
        INCURRED, THAT MAY BE ASSERTED BY ANY PERSONS OR
        ENTITIES ARISING OUT OF OR RELATED TO THE PRIMARY
        OWNER&apos;S USE AND/OR SUBLICENSING OF THE FROGGY FRIENDS
        NFT AND RELATED ART FOR COMMERCIAL PURPOSES, AS WELL
        AS ANY BREACH OF SUCH INDEMNIFYING PARTY&apos;S
        WARRANTIES AND REPRESENTATIONS IN THIS AGREEMENT.
      </p>
    </>
  )
}